version: '3.7'

services:
  backend-ox:
    container_name: bakend-ox
    build:
      context: .
      dockerfile: Dockerfile
      # target: builder
    # env_file:
    #   - .env
    volumes:
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
    expose:
      - '5000'
    ports:
      - '5000:5000'
    command: yarn dev
    # depends_on:
    #   - mongo-db
  
  mongo-db:
    container_name: mongo-db
    image: mongo:6-jammy
    ports:
      - '27017'
    volumes:
      - dbdata6:/data/db
volumes:
  dbdata6:
